### ISSUE TITLE
[Bug] `standardized-audio-context` is off beat and glitching

### ISSUE THREAD

**Issue by IRod22** [chrisguttandin/standardized-audio-context#993] opened 2022-07-10 22:05 UTC
I am having a potential issue with this library, which links to [Tone.js](https://github.com/Tonejs/Tone.js), particularly with Tonejs/Tone.js#1096. In that issue, I pinpointed the bug to either be in Tone.js or this library; that is why I'm here to see if this package is what is making Tone.js sound glitchy and off beat.

**Comment by chrisguttandin** [comment] 2022-07-21 16:06
Hi @IRod22, I tried to reproduce the issues with your example on StackBlitz but it worked as expected for me.

Can you please double check if it is a problem with standardized-audio-context or with Tone.js by setting the `AudioContext` used by Tone.js to the native `AudioContext`?

https://tonejs.github.io/docs/14.7.33/fn/setContext

I think the following should work:

```js
Tone.setContext(window.AudioContext);
```

**Comment by IRod22** [comment] 2022-07-21 18:40
I just tried that on my Windows machine, and the browser gave me the following error:
```
TypeError: Ii.resume is not a function
```

I'll have to get you the call stack later (currently offline), but I can tell you that it happend in the following snippet (pretty-printed as I was using the min.js version):
```js
function Pi() {
    return Ii.resume()
}
```

**Comment by chrisguttandin** [comment] 2022-07-21 21:33
The snippet that I posted above is wrong. Sorry for that. It should be an instance of an `AudioContext` and not the constructor.

```js
Tone.setContext(new window.AudioContext());
```

**Comment by IRod22** [comment] 2022-07-21 21:56
Got a new error:
![20220721_165127](https://user-images.githubusercontent.com/104603218/180321613-99088c98-0180-47d0-ab5f-468c08fc773d.jpg) that is much deeper in the call stack. I'll get a "dev" version of Tone.js to comb through the call stack.

**Comment by chrisguttandin** [comment] 2022-07-21 22:02
I updated your example on StackBlitz. It works without throwing any errors for me in Chrome.

https://stackblitz.com/edit/tonejs-issue-playing-and-timing-cqqyoj

It fails in Firefox and for sure in Safari. That's why Tone.js uses this library. :-) But I thought the bug that you are reporting only happens in Chrome.

**Comment by IRod22** [comment] 2022-07-21 22:25
It happens in Firefox (desktop and Android),  Chrome for Android, and Samsung Internet. This is why I created this issue here to see if this library is the root of the bug. See the original issue thread for details.

**Comment by chrisguttandin** [comment] 2022-07-21 22:41
Yes, I looked at the other issue that's how I got to know that it's a Chrome only issue. The original bug says it happens in Firefox but later one you wrote:

> This testing allows me to conclude that this is either with the Tone.js API, or with the Web Audio API on Chromium-based browsers.

Sadly I have no way to reproduce the issue. It works as expected for me in Firefox, too.

**Comment by IRod22** [comment] 2022-07-21 22:57
Wow. We may need to have the community chime in to reproduce the bug on their machines. What's strange to me is that I tested this out on two different devices, one relatively old and one relatively new, and the issue still cropped up on different browsers.

**Comment by chrisguttandin** [comment] 2022-08-16 20:49
I'm going to close the issue over here. The problem isn't solved yet but I think it's confusing to have the same conversation twice.

tonejs/Tone.js#1096

**Closed by chrisguttandin** 2022-08-16 20:49 UTC
