### ISSUE TITLE
Issue with Safari

### ISSUE THREAD

**Issue by jrm2k6** [chrisguttandin/standardized-audio-context#707] opened 2019-10-04 22:49 UTC
Hi @chrisguttandin.

Code example: https://codesandbox.io/s/optimistic-payne-b4px4

A few things:
- I am using a MediaRecorder [polyfill](https://github.com/ai/audio-recorder-polyfill) to support MediaRecorder in Safari/Edge.
- I am also using [audio buffer utils](https://github.com/audiojs/audio-buffer-utils)
- I want to slice the recording in 2 sec segments but also want to keep the recording locally (by concatenating the different buffers as I will have some post-processing on the backend) but still want the user to be able to play the audio immediately.

This works fine in Chrome, but seems to not be generating a correct final blob on Safari.

I also noticed that `getByteFrequencyData` is returning an array of 0 when connecting an analyser (AudioContext.createAnalyser) on Safari, whereas Chrome works fine (haven't tried Firefox yet but I usually don't have issues with it).

Any idea where the issue could be? I am happy to provide more details if needed, as I know the combination of the polyfills I am using could very well be the cause.

**Comment by chrisguttandin** [comment] 2019-10-05 08:22
Hi @jrm2k6,

thanks for the detailed report. However I think the problem is unrelated to this library. Safari requires the type of the Blob to be defined. https://codesandbox.io/s/friendly-williamson-7uiwg I only changed line 47 of your example.

You can probably get rid of standardized-audio-context completely. You could try concatenating the ArrayBuffers directly.

I will close this issue now since I believe it is unrelated to standardized-audio-context. Feel free to reopen it if you disagree or to open a new one if you run into any other issues.

**Closed by chrisguttandin** 2019-10-05 08:22 UTC

**Comment by jrm2k6** [comment] 2019-10-07 17:48
@chrisguttandin 
Thanks for the answer, it seems to be working.
I am pretty new to Audio in javascript. I didn't see anything about having to specify the blob type for Safari only. How did you figure that out? 

For the other issue I mentioned, it seems that the analyzer wasn't connecting correctly to the stream, due to where I was instantiating the audiocontext. I remember seeing that Safari required instantiating the AudioContext as part of the user event handler, but when using standardized audio context, it actually makes it fail the first time you try to connect. I am not sure I understand why.

**Comment by chrisguttandin** [comment] 2019-10-07 18:08
> I didn't see anything about having to specify the blob type for Safari only. How did you figure that out?

I had to search for many bugs in Safari over the years. Maybe I developed an instinct for it. :-)

> I remember seeing that Safari required instantiating the AudioContext as part of the user event handler, but when using standardized audio context, it actually makes it fail the first time you try to connect. I am not sure I understand why.

I'm not sure if I understand the issue. Can you please elaborate a little more or point me to the line of code where it fails?
