### ISSUE TITLE
problem with AudioContext.decodeAudioData in sfari 12

### ISSUE THREAD

**Issue by MHA15** [chrisguttandin/standardized-audio-context#718] opened 2019-10-17 17:43 UTC
I was trying to extract audio from a video but in safari 12 (ios) it not works write and it's error is not clear enough  it `Unhandled Promise Rejection: Encoding Error`

**Comment by chrisguttandin** [comment] 2019-10-17 20:04
Hi @MHA15,

I'm not sure if this is something that can be fixed with this library. An `EncodingError` is what gets thrown by `decodeAudioData()` when the browser doesn't understand the codec. So it most likely just means that Safari can't decode the file.

Is the file available somewhere on the internet for me to reproduce the issue? Does it work in other browsers?

**Comment by MHA15** [comment] 2019-10-21 07:57
there is no special file any mp4 file in ios will cause this error
and yes it works correctly on other browsers

**Comment by chrisguttandin** [comment] 2019-10-21 15:02
Since the goal of this package is to achieve spec compliance in all browsers I still think there is nothing we need to do here. As mentioned above throwing an `EncodingError` is totally fine if the browser can't handle the file. Here is a link to the relevant part of the spec: https://webaudio.github.io/web-audio-api/#dom-baseaudiocontext-decodeaudiodata.

Decodethis is a page which might be helpful when checking for support of various file formats in different browsers: https://chinmay.audio/decodethis. There is also an mp4 file in the test suite.

Another thing you could try is to extract the audio inside the mp4 container yourself and pass only the audio data to `decodeAudioData()`. I successfully used that technique in the past. But it might be easier to just re-encode the file for iOS.

**Closed by chrisguttandin** 2019-10-21 15:02 UTC

**Comment by MHA15** [comment] 2019-10-21 20:18
maybe I'am misunderstanding something
Isn't this library for implementing AudioContext API to make sure that everything will work fine in everywhere? 
I'am using AudioContext.decodeAudioData to decode and get AudioBuffer from a video file (which will work in chrome on my system but it will fails in safari on ios) now what is `Encoding Error` shouldn't we implement a decoder which can decode every video file (we can implement it by js couldn't we?) 
I heard that [videoconverter.js](https://bgrins.github.io/videoconverter.js/demo/) can do this and we can decode a video using it even on an ios device
